export const DEFAULT_MARKDOWN = [
  '---',
  'title: Another Markdown Viewer',
  'description: A focused Vite and TypeScript workspace for editing, previewing, and exporting Markdown.',
  'author: ransuhaneda',
  'tags: [markdown, live-preview, gfm, open-source]',
  '---',
  '',
  '# Another Markdown Viewer',
  '',
  '> A focused, browser-based Markdown editor. Edit your source, inspect the rendered document, and export a polished PDF.',
  '',
  '![Another Markdown Viewer workspace](/images/another-markdown-viewer-workspace.svg)',
  '',
  '*An example workspace illustration, stored with the project.*',
  '',
  '## Built for a simple Markdown workflow',
  '',
  'Another Markdown Viewer keeps the source and rendered document together. Paste Markdown, make a few edits, and check the result before you share or print it.',
  '',
  '- **Source Markdown** keeps the original Markdown visible while you edit.',
  '- **Rendered View** shows the formatted document as you make changes.',
  '- **Split view** lets you compare source and rendered output side by side.',
  '- **Automatic recovery** restores your latest working draft in this browser.',
  '- **PDF export** produces a print-ready document from the preview.',
  '',
  '> [!NOTE]',
  '> Your Markdown remains the source of truth. Local recovery helps restore a draft; use Save Markdown to download a file you can keep.',
  '',
  '## Markdown features',
  '',
  '### Headings and formatting',
  '',
  '# Heading 1',
  '## Heading 2',
  '### Heading 3',
  '#### Heading 4',
  '##### Heading 5',
  '###### Heading 6',
  '',
  '- **Bold text**',
  '- *Italic text*',
  '- ***Bold and italic text***',
  '- ~~Strikethrough text~~',
  '- Inline code such as `pnpm run build`',
  '',
  '### Code',
  '',
  'Use `pnpm install` to install the project dependencies.',
  '',
  '```typescript',
  'const product = {',
  '  name: "Another Markdown Viewer",',
  '  format: "GitHub-Flavored Markdown",',
  '  preview: "rendered",',
  '}',
  '',
  'console.log(`Ready to write: ${product.name}`)',
  '```',
  '',
  '### Links and images',
  '',
  'The application runs in your browser. [Return to the viewer](./) or [jump to installation](#installation).',
  '',
  '![Another Markdown Viewer editor and rendered preview](/images/another-markdown-viewer-preview.svg)',
  '',
  '*A local illustration of the editor and rendered document panes.*',
  '',
  '**Clickable image:**',
  '',
  '[![Open Another Markdown Viewer](/images/another-markdown-viewer-workspace.svg)](./)',
  '',
  '### Lists and tasks',
  '',
  '1. Paste or open a Markdown document.',
  '2. Edit the source Markdown.',
  '3. Inspect the rendered result.',
  '4. Save the Markdown file or export a PDF.',
  '',
  '- The editor and preview scroll independently.',
  '  - Switch to split view to compare them.',
  '  - Use the layout controls to focus on one pane.',
  '',
  '- [x] Edit Markdown in the browser',
  '- [x] Inspect the rendered document',
  '- [ ] Download a PDF when the document is ready',
  '',
  '### A useful note',
  '',
  '> [!TIP]',
  '> Edit the source when you need precise control over Markdown syntax or spacing.',
  '',
  '> [!IMPORTANT]',
  '> The browser keeps one latest recovery draft. Download Markdown to keep an independent copy.',
  '',
  '> [!WARNING]',
  '> If browser storage is unavailable, the current session remains editable but may not be recovered after closing the page.',
  '',
  '> [!CAUTION]',
  '> Clearing the draft removes its local recovery data.',
  '',
  '### Tables',
  '',
  '| Workspace area | Purpose |',
  '| :--- | :---: |',
  '| Editor | Write and update Markdown |',
  '| Rendered View | Check the formatted document |',
  '| PDF export | Print or save the rendered result |',
  '',
  '### Blockquotes',
  '',
  '> Keep the writing flow simple.',
  '>',
  '> > Make small edits, check the preview, and save a copy when you need one.',
  '',
  '### Details',
  '',
  '<details>',
  '<summary>About this example document</summary>',
  '',
  'This editable example introduces Another Markdown Viewer and demonstrates supported Markdown features using local project illustrations.',
  '',
  '</details>',
  '',
  '### Escaping Markdown',
  '',
  '- \\*This text keeps its asterisks.\\*',
  '- \\# This line stays a paragraph.',
  '- \\- This line is not a list item.',
  '',
  '### HTML comment',
  '',
  '<!-- This source comment is not part of the rendered document. -->',
  '',
  '### Project structure',
  '',
  '```text',
  'another-markdown-viewer/',
  '├── public/',
  '│   └── images/',
  '├── src/',
  '│   ├── app/',
  '│   ├── editor/',
  '│   ├── markdown/',
  '│   └── persistence/',
  '├── tests/',
  '├── index.html',
  '└── package.json',
  '```',
  '',
  '### Installation',
  '',
  'Install the project dependencies and start the local Vite development server:',
  '',
  '```bash',
  'pnpm install',
  'pnpm dev',
  '```',
  '',
  'The project uses CodeMirror 6, a GitHub-Flavored Markdown parser, DOMPurify, and `browser-fs-access`. Cloudflare Pages is the initial deployment target.',
  '',
  '### Diff example',
  '',
  '```diff',
  '- const preview = "static";',
  '+ const preview = "live";',
  '```',
  '',
  '---',
  '',
  '## Keyboard shortcuts',
  '',
  '| Shortcut | Action |',
  '| --- | --- |',
  '| `Ctrl/Cmd+B` | Toggle bold |',
  '| `Ctrl/Cmd+I` | Toggle italic |',
  '| `Ctrl/Cmd+K` | Insert a link |',
  '| `Ctrl/Cmd+S` | Save Markdown |',
  '| `Ctrl/Cmd+Shift+F` | Toggle Focus mode |',
  '',
  'Open **Markdown help** for the full syntax reference and keyboard shortcut list.',
  '',
  '---',
  '',
  'Made for a clear Markdown workflow with **Another Markdown Viewer**.',
  '',
].join('\n')
