export const DEFAULT_MARKDOWN = [
  '# Common Markdown + GitHub-Flavored Markdown',
  '',
  '## Headings',
  '',
  '# Heading 1',
  '## Heading 2',
  '### Heading 3',
  '#### Heading 4',
  '##### Heading 5',
  '###### Heading 6',
  '',
  '',
  '## Bold',
  '',
  '**Bold text**',
  '',
  '',
  '## Italic',
  '',
  '*Italic text*',
  '',
  '',
  '## Bold + Italic',
  '',
  '***Bold and italic text***',
  '',
  '',
  '## Strikethrough — GFM',
  '',
  '~~Strikethrough text~~',
  '',
  '',
  '## Inline Code',
  '',
  'Use `npm install` to install dependencies.',
  '',
  '',
  '## Code Block',
  '',
  '```javascript',
  'const message = "Hello World";',
  '',
  'console.log(message);',
  '```',
  '',
  '',
  '## Blockquote',
  '',
  '> This is a blockquote.',
  '',
  '',
  '## Nested Blockquote',
  '',
  '> First level',
  '>',
  '> > Second level',
  '',
  '',
  '## Unordered List',
  '',
  '- Item 1',
  '- Item 2',
  '- Item 3',
  '',
  '',
  '## Nested List',
  '',
  '- Parent item',
  '- Child item',
  '- Child item',
  '',
  '',
  '## Ordered List',
  '',
  '1. First item',
  '2. Second item',
  '3. Third item',
  '',
  '',
  '## Mixed List',
  '',
  '1. First item',
  '- Sub-item',
  '- Sub-item',
  '2. Second item',
  '',
  '',
  '## Task List — GFM',
  '',
  '- [x] Completed',
  '- [ ] In progress',
  '- [ ] Not started',
  '',
  '',
  '## Link',
  '',
  '[OpenAI](openai.com)',
  '',
  '',
  '## Automatic Link',
  '',
  '<github.com>',
  '',
  '',
  '## Image',
  '',
  '![Alt text](picsum.photos/200/300)',
  '',
  '',
  '## Clickable Image',
  '',
  '[![Alt text](picsum.photos/200)](example.com)',
  '',
  '',
  '## Horizontal Rule',
  '',
  '---',
  '',
  '',
  '## Table — GFM',
  '',
  '| Name | Role | Status |',
  '| --- | --- | --- |',
  '| Elaine | Designer | Active |',
  '| Alex | Developer | Active |',
  '',
  '',
  '## Table Alignment — GFM',
  '',
  '| Left | Center | Right |',
  '| :--- | :---: | ---: |',
  '| Text | Text | 100 |',
  '| Text | Text | 200 |',
  '',
  '',
  '## Escaping Markdown',
  '',
  '\\*Not italic\\*',
  '',
  '\\# Not a heading',
  '',
  '\\- Not a list',
  '',
  '',
  '## HTML',
  '',
  '<br>',
  '',
  '<details>',
  '<summary>Show more</summary>',
  '',
  'Hidden content.',
  '',
  '</details>',
  '',
  '',
  '## Comments',
  '',
  '<!-- This will not appear when rendered -->',
  '',
  '',
  '## GitHub Alerts — GFM',
  '',
  '> [!NOTE]',
  '> Useful information.',
  '',
  '> [!TIP]',
  '> Helpful advice.',
  '',
  '> [!IMPORTANT]',
  '> Important information.',
  '',
  '> [!WARNING]',
  '> Something requires attention.',
  '',
  '> [!CAUTION]',
  '> Potential consequences.',
  '',
  '',
  '## GitHub Mentions',
  '',
  '@username',
  '',
  '',
  '## Issue / Pull Request Reference',
  '',
  '#123',
  '',
  'owner/repository#123',
  '',
  '',
  '## Relative File Link',
  '',
  '[Documentation](./docs/README.md)',
  '',
  '',
  '## Heading Link',
  '',
  '[Go to Installation](#installation)',
  '',
  '## Installation',
  '',
  'Content here.',
  '',
  '',
  '## File Tree',
  '',
  '```text',
  'project/',
  '├── src/',
  '│ ├── components/',
  '│ └── pages/',
  '├── public/',
  '├── package.json',
  '└── README.md',
  '```',
  '',
  '',
  '## Diff Block',
  '',
  '```diff',
  '- const oldValue = false;',
  '+ const newValue = true;',
  '```',
  '',
  '',
  '## Combined Example',
  '',
  '# Project Name',
  '',
  'Short project description.',
  '',
  '## Features',
  '',
  '- [x] Responsive design',
  '- [x] TypeScript',
  '- [ ] Authentication',
  '',
  '## Installation',
  '',
  '```bash',
  'npm install',
  'npm run dev',
  '```',
  '',
  '## Status',
  '',
  '| Feature | Status |',
  '| --- | --- |',
  '| Homepage | ✅ Complete |',
  '| Dashboard | 🚧 In Progress |',
  '',
  '> [!NOTE]',
  '> Requires Node.js 24 or newer.',
  '',
  'For more information, see the [documentation](./docs/README.md).',
  '',
].join('\n')
